# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 325bef39617454255fe40d31660d47ee38ae10cf02cbfbaa8507a475956b4c573266cf8aef9f38fcb4583388550428ddd80a92e2f5484bd58c6d9188c775c324

test:
  secret_key_base: 020a08b236bed139943f1b9373bdcfda316366fd3b36c46caf27282dab119d55cb5263310e7a64c421542742ba4c73a586c5c5e5f9f02a5c935b8c48fea7b7d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
